[package]
name = "hypercore-protocol"
version = "0.3.1"
license = "MIT OR Apache-2.0"
description = "Replication protocol for Hypercore feeds"
authors = ["Franz Heinzmann (Frando) <frando@unbiskant.org>"]
documentation = "https://docs.rs/hypercore-protocol"
repository = "https://github.com/Frando/hypercore-protocol-rs"
readme = "README.md"
edition = "2018"
keywords = ["dat", "p2p", "replication", "hypercore", "protocol"]
categories = [
  "asynchronous",
  "concurrency",
  "cryptography",
  "data-structures",
  "encoding",
]

[lib]
# benchmarks are using criterion
bench = false

[dependencies]
async-channel = "1.5"
# FIXME: Once there is a new version of snow with fix to rc.0 compilation break, switch to it.
# snow = { version = "0.9.0", features = ["risky-raw-split"] }
snow = { git = "https://github.com/tarcieri/snow", branch = "curve25519-dalek/v4.0.0-rc.0", features = ["risky-raw-split"] }
prost = { version = "0.7", optional = true }
bytes = "1.0.1"
varinteger = { version = "1.0", optional = true }
rand = "0.8"
blake2-rfc = "0.2"
hex = "0.4"
async-trait = "0.1.63"
salsa20 = "0.6"
log = "0.4"
pretty-hash = "0.4"
futures-timer = "3.0"
instant = "0.1"
getrandom = "0.1"
futures-lite = "1.11.3"
hypercore = { git = "https://github.com/ttiurani/hypercore", branch = "tokio", default-features = false }
sha2 = "0.10.6"
# FIXME: This uses pre-release, because v4 relaxed the zeroize version range. With this the crate be
# buildable with other crates that use zeroize >=1.5. When 4.0 releases, switch to that.
curve25519-dalek = "4.0.0-rc.0"
crypto_secretstream = { version = "0.1.1", optional = true }

[dev-dependencies]
async-std = { version = "1.12.0", features = ["attributes", "unstable"] }
async-compat = "0.2.1"
tokio = { version = "1.25.0", features = ["macros", "net", "process", "rt", "rt-multi-thread", "sync", "time"] }
env_logger = "0.7.1"
random-access-storage = { git = "https://github.com/ttiurani/random-access-storage", branch = "tokio"}
random-access-disk = { git = "https://github.com/ttiurani/random-access-disk", branch = "tokio" }
random-access-memory = { git = "https://github.com/ttiurani/random-access-memory", branch = "tokio" }
anyhow = "1.0.28"
criterion = { version = "0.4", features = ["async_std"] }
pretty-bytes = "0.2.2"
duplexify = "1.1.0"
sluice = "0.5.4"
futures = "0.3.13"
cfg-if = "1.0"

[build-dependencies]
prost-build = { version = "0.6.1", optional = true }

[features]
default = ["v10", "async-std"]
wasm-bindgen = [
  "instant/wasm-bindgen", 
  "getrandom/wasm-bindgen", 
  "futures-timer/wasm-bindgen"
]
v9 = ["prost", "prost-build", "varinteger", "hypercore/v9",]
v10 = ["hypercore/v10", "crypto_secretstream"]
tokio = ["hypercore/tokio", "random-access-disk/tokio"]
async-std = ["hypercore/async-std", "random-access-disk/async-std"]
# Used only in interoperability tests under tests/js-interop which use the javascript version of hypercore
# to verify that this crate works. To run them, use:
# cargo test --features js-interop-tests
js_interop_tests = []

[profile.bench]
# debug = true

[profile.release]
# debug = true

[[bench]]
name = "throughput"
harness = false

[[bench]]
name = "pipe"
harness = false
