[package]
name = "hypercore-protocol"
version = "0.3.1"
license = "MIT OR Apache-2.0"
description = "Replication protocol for Hypercore feeds"
authors = ["Franz Heinzmann (Frando) <frando@unbiskant.org>"]
documentation = "https://docs.rs/hypercore-protocol"
repository = "https://github.com/Frando/hypercore-protocol-rs"
readme = "README.md"
edition = "2018"
keywords = ["dat", "p2p", "replication", "hypercore", "protocol"]
categories = [
  "asynchronous",
  "concurrency",
  "cryptography",
  "data-structures",
  "encoding",
]

[lib]
# benchmarks are using criterion
bench = false

[dependencies]
async-channel = "1.5"
snow = { version = "0.9.0", features = ["risky-raw-split"] }
prost = { version = "0.7", optional = true }
bytes = "1.0.1"
varinteger = { version = "1.0", optional = true }
rand = "0.7"
blake2-rfc = "0.2"
hex = "0.4"
async-trait = "0.1"
salsa20 = "0.6"
log = "0.4"
pretty-hash = "0.4"
futures-timer = "3.0"
instant = "0.1"
getrandom = "0.1"
futures-lite = "1.11.3"

[dev-dependencies]
async-std = { version = "1.9.0", features = ["attributes", "unstable"] }
env_logger = "0.7.1"
hypercore = { git = "https://github.com/ttiurani/hypercore", branch = "v10", default-features = false }
random-access-disk = { git = "https://github.com/ttiurani/random-access-disk", branch = "v10" }
random-access-memory = { git = "https://github.com/ttiurani/random-access-memory", branch = "v10" }
random-access-storage = "4.0.0"
anyhow = "1.0.28"
criterion = "0.3.2"
pretty-bytes = "0.2.2"
duplexify = "1.1.0"
sluice = "0.5.4"
futures = "0.3.13"
cfg-if = "1.0"

[build-dependencies]
prost-build = { version = "0.6.1", optional = true }

[features]
default = ["v10"]
wasm-bindgen = [
  "instant/wasm-bindgen", 
  "getrandom/wasm-bindgen", 
  "futures-timer/wasm-bindgen"
]
v9 = ["prost", "prost-build", "varinteger", "hypercore/v9",]
v10 = ["hypercore/v10"]

[profile.bench]
# debug = true

[profile.release]
# debug = true

[[bench]]
name = "throughput"
harness = false

[[bench]]
name = "pipe"
harness = false
